apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    autoscaling.alpha.kubernetes.io/metrics: '[{"type":"Resource","resource":{"name":"memory","targetAverageUtilization":99}}]'
  name: hpa2
spec:
  maxReplicas: 100
  minReplicas: 100
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: scaling-strategy-deploy2
  targetCPUUtilizationPercentage: 99