apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa4
spec:
  maxReplicas: 100
  minReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: scaling-strategy-deploy4
  targetCPUUtilizationPercentage: 50