apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    group: scaling-strategy-test
  name: scaling-strategy-deploy1
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.es.io: deployment.scaling-strategy-deploy2
  template:
    metadata:
      labels:
        workload.es.io: deployment.scaling-strategy-deploy2
        group: upgrade-strategy-test
    spec:
      containers:
        - image: 'nginx:latest'
          imagePullPolicy: IfNotPresent
          name: scaling-strategy-deploy2
        

