name: ecnf-load

namespace:
  number: 1

tuningSets:
- name: Sequence
  parallelismLimitedLoad:
    parallelismLimit: 1

- name: default
  globalQPSLoad:
    qps: 1
    burst: 1

steps:

 - module:
     path: modules/name-type-test/main.yaml
     params:
       actionName: "create"
       namespaces: 1
       tuningSet: Sequence
       operationTimeout: 15m

 - module:
     path: modules/env-variable-test/main.yaml
     params:
       actionName: "create"
       namespaces: 1
       tuningSet: Sequence
       operationTimeout: 15m

 - module:
     path: modules/volume-test/main.yaml
     params:
       actionName: "create"
       namespaces: 1
       tuningSet: Sequence
       operationTimeout: 15m

 - module:
     path: modules/security-setting-test/main.yaml
     params:
       actionName: "create"
       namespaces: 1
       tuningSet: Sequence
       operationTimeout: 15m

 - module:
     path: modules/command-test/main.yaml
     params:
       actionName: "create"
       namespaces: 1
       tuningSet: Sequence
       operationTimeout: 15m

 - module:
     path: modules/access-type-test/main.yaml
     params:
       actionName: "create"
       namespaces: 1
       tuningSet: Sequence
       operationTimeout: 15m

 - module:
     path: modules/label-test/main.yaml
     params:
       actionName: "create"
       namespaces: 1
       tuningSet: Sequence
       operationTimeout: 15m

 - module:
     path: modules/wordpress/main.yaml
     params:
       actionName: "create"
       namespaces: 1
       tuningSet: Sequence
       operationTimeout: 15m

 - module:
     path: modules/nodeport/main.yaml
     params:
       actionName: "create"
       namespaces: 1
       tuningSet: Sequence
       operationTimeout: 15m

 - module:
     path: modules/ingress/main.yaml
     params:
       actionName: "create"
       namespaces: 1
       tuningSet: Sequence
       operationTimeout: 15m

 - module:
     path: modules/env-test/main.yaml
     params:
       actionName: "create"
       namespaces: 1
       tuningSet: Sequence
       operationTimeout: 15m

 - module:
     path: modules/html-test/main.yaml
     params:
       actionName: "create"
       namespaces: 1
       tuningSet: Sequence
       operationTimeout: 15m

 - module:
     path: modules/pvc-test/main.yaml
     params:
       actionName: "create"
       namespaces: 1
       tuningSet: Sequence
       operationTimeout: 15m

 - module:
     path: modules/resource-test/main.yaml
     params:
       actionName: "create"
       namespaces: 1
       tuningSet: Sequence
       operationTimeout: 15m

# - module:
#     path: modules/health-check-test/main.yaml
#     params:
#       actionName: "create"
#       namespaces: 1
#       tuningSet: Sequence
#       operationTimeout: 15m

 - module:
     path: modules/clusterip/main.yaml
     params:
       actionName: "create"
       namespaces: 1
       tuningSet: Sequence
       operationTimeout: 15m

 - module:
     path: modules/upgrade-strategy-test/main.yaml
     params:
       actionName: "create"
       namespaces: 1
       tuningSet: Sequence
       operationTimeout: 15m
