apiVersion: v1
kind: Service
metadata:
  name: mariadb-svc
  annotations:
    ovn.kubernetes.io/vpc: ovn-cluster
    workload.es.io/kind: statefulset
    workload.es.io/name: mariadb
spec:
  selector:
    workload.es.io: statefulset.mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
