apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  labels:
    group: wordpress
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      workload.es.io: statefulset.mariadb
  template:
    metadata:
      labels:
        workload.es.io: statefulset.mariadb
        group: wordpress
    spec:
      containers:
      - name: mariadb
        image: 'hub.ecns.io/library/mariadb:latest'
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: '2'
            memory: 2Gi
          requests:
            cpu: '2'
            memory: 2Gi
        ports:
        - containerPort: 3306
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: mariadb-root-password
        - name: MARIADB_DATABASE
          value: wordpress
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: mariadb-pv
      schedulerName: default-scheduler
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: mariadb-pv
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: cinder
        volumeMode: Filesystem
