apiVersion: v1
kind: Service
metadata:
  annotations:
    ovn.kubernetes.io/vpc: ovn-cluster
    workload.es.io/kind: deployment
    workload.es.io/name: wordpress
  name: wordpress-svc
spec:
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 30881
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    workload.es.io: deployment.wordpress
  type: NodePort
