apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    group: label-test
    ABCDEFGHIJKLMNOPQRSTUVWXYZ-abcdefghijklmnopqrstuvwxyz_0.9.9.9.9: ABCDEFGHIJKLMNOPQRSTUVWXYZ-abcdefghijklmnopqrstuvwxyz_0.9.9.9.9
    a: '1'
    app: foo
  name: labels-test-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.es.io: deployment.labels-test-deploy
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.es.io: deployment.labels-test-deploy
    spec:
      containers:
        - image: 'hub.ecns.io/library/centos:alltools'
          imagePullPolicy: IfNotPresent
          name: labels-test-deploy
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 512Mi