apiVersion: v1
kind: Service
metadata:
  name: clsip-nginx-svc
  annotations:
    ovn.kubernetes.io/vpc: ovn-cluster
    workload.es.io/kind: deployment
    workload.es.io/name: nginx-dpm
spec:
  selector:
    workload.es.io: deployment.nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: ClusterIP