apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clsip-httpd-sts
  labels:
    group: cluster-ip
spec:
  podManagementPolicy: OrderedReady
  replicas: 2
  selector:
    matchLabels:
      workload.es.io: statefulset.httpd
  serviceName: ''
  template:
    metadata:
      labels:
        workload.es.io: statefulset.httpd
        group: cluster-ip
    spec:
      containers:
        - image: 'hub.ecns.io/library/httpd:latest'
          name: httpd
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
              nvidia.com/gpu: '0'
            requests:
              cpu: 250m
              memory: 512Mi
              nvidia.com/gpu: '0'