apiVersion: v1
kind: Service
metadata:
  name: clsip-httpd-svc
  annotations:
    ovn.kubernetes.io/vpc: ovn-cluster
    workload.es.io/kind: statefulset
    workload.es.io/name: httpd-sts
spec:
  selector:
    workload.es.io: statefulset.httpd
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
  type: ClusterIP