apiVersion: v1
kind: Service
metadata:
  name: clsip-tomcat-svc
  annotations:
    ovn.kubernetes.io/vpc: ovn-cluster
    workload.es.io/kind: daemonset
    workload.es.io/name: tomcat-ds
spec:
  selector:
    workload.es.io: daemonset.tomcat
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8080
  type: ClusterIP