apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    group: upgrade-strategy-test
  name: upgrade-strategy-deploy1
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.es.io: deployment.upgrade-strategy-deploy1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.es.io: deployment.upgrade-strategy-deploy1
        group: upgrade-strategy-test
    spec:
      containers:
        - image: 'nginx:latest'
          imagePullPolicy: IfNotPresent
          name: upgrade-strategy-deploy1
        

