apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    group: upgrade-strategy-test
  name: upgrade-strategy-dms1
spec:
  selector:
    matchLabels:
      workload.es.io: daemonset.upgrade-strategy-dms1
  template:
    metadata:
      labels:
        workload.es.io: daemonset.upgrade-strategy-dms1
    spec:
      containers:
        - image: 'nginx:latest'
          imagePullPolicy: IfNotPresent
          name: upgrade-strategy-dms1
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate