apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    group: upgrade-strategy-test
  name: upgrade-strategy-deploy4
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.es.io: deployment.upgrade-strategy-deploy4
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        workload.es.io: deployment.upgrade-strategy-deploy4
        group: upgrade-strategy-test
    spec:
      containers:
        - image: 'nginx:latest'
          imagePullPolicy: IfNotPresent
          name: upgrade-strategy-deploy4
        

