apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nodeport-sts
  labels:
    group: nodeport
spec:
  replicas: 2
  selector:
    matchLabels:
      workload.es.io: statefulset.nodeport
  template:
    metadata:
      labels:
        workload.es.io: statefulset.nodeport
        group: nodeport
    spec:
      containers:
        - image: 'httpd:latest'
          name: httpd
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 512Mi