apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nodeport-ds
  labels:
    group: nodeport
spec:
  selector:
    matchLabels:
      workload.es.io: daemonset.nodeport
  template:
    metadata:
      labels:
        workload.es.io: daemonset.nodeport
        group: nodeport
    spec:
      containers:
        - image: 'tomcat:latest'
          name: tomcat
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 512Mi