apiVersion: v1
kind: Service
metadata:
  name: nodeport-dpm-svc
  annotations:
    ovn.kubernetes.io/vpc: ovn-cluster
    workload.es.io/kind: deployment
    workload.es.io/name: nodeport-dpm
spec:
  selector:
    workload.es.io: deployment.nodeport
  ports:
    - nodePort: 30887
      port: 80
      protocol: TCP
      targetPort: 80
  type: NodePort