apiVersion: v1
kind: Service
metadata:
  annotations:
    ovn.kubernetes.io/vpc: ovn-cluster
    workload.es.io/kind: deployment
    workload.es.io/name: clusterip-deploy
  name: te-1
spec:
  ports:
    - name: name65535
      port: 65535
      protocol: TCP
      targetPort: 1
    - name: name1
      port: 1
      protocol: UDP
      targetPort: 65535
    - name: name33333
      port: 33333
      protocol: TCP
      targetPort: 33333
  selector:
    workload.es.io: deployment.clusterip-deploy
  type: ClusterIP