apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    group: access-type-test
  name: clusterip-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.es.io: deployment.clusterip-deploy
  template:
    metadata:
      labels:
        workload.es.io: deployment.clusterip-deploy
        group: access-type-test
    spec:
      containers:
        - image: 'hub.ecns.io/library/centos:alltools'
          imagePullPolicy: IfNotPresent
          name: clusterip-deploy