apiVersion: v1
kind: Service
metadata:
  annotations:
    ovn.kubernetes.io/vpc: ovn-cluster
    workload.es.io/kind: deployment
    workload.es.io/name: nodeport-deploy
  name: testtest0123456789test-1
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: name1
      nodePort: 30124
      port: 1
      protocol: TCP
      targetPort: 1
    - name: name65535
      nodePort: 30000
      port: 65535
      protocol: UDP
      targetPort: 65535
    - name: name32155
      nodePort: 32767
      port: 32155
      protocol: TCP
      targetPort: 32155
    - name: name55555
      nodePort: 32222
      port: 55555
      protocol: UDP
      targetPort: 55555
  selector:
    workload.es.io: deployment.nodeport-deploy
  type: NodePort