apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvc-test-dpm
  labels:
    group: nginx-pvc
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.es.io: deployment.nginx
  template:
    metadata:
      labels:
        workload.es.io: deployment.nginx
        group: nginx-pvc
    spec:
      containers:
        - image: 'hub.ecns.io/library/nginx:latest'
          name: nginx
          volumeMounts:
            - mountPath: /data
              name: vol1
      volumes:
        - name: vol1
          persistentVolumeClaim:
            claimName: pvc-test

